import { useMemo } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { Button, Chip, Container, Dropdown, EmptyState, PageHeading, SearchBar } from '@/components/ui'
import { ROUTES } from '@/constants/routes'
import { getContests } from '@/services/dataService'

const SORT_OPTIONS = [{ value: 'new', label: 'Сначала новые' }, { value: 'prize', label: 'По размеру награды' }]
const formatDate = (date) => new Intl.DateTimeFormat('ru-RU', { day: 'numeric', month: 'long' }).format(new Date(date))

function ContestCard({ contest }) {
  return <article className="group flex h-full flex-col overflow-hidden rounded-2xl border border-line bg-white transition-[translate,box-shadow] duration-300 hover:-translate-y-1 hover:shadow-card"><Link to={ROUTES.contest(contest.id)} className="block aspect-[16/8] overflow-hidden bg-lavender"><img src={contest.cover} alt="" className="size-full object-cover transition-transform duration-700 group-hover:scale-105" /></Link><div className="flex flex-1 flex-col p-5"><div className="flex items-center justify-between gap-3 text-xs text-muted"><span>{contest.category}</span><span>До {formatDate(contest.deadline)}</span></div><h2 className="mt-3 text-lg font-semibold leading-snug"><Link to={ROUTES.contest(contest.id)} className="hover:text-primary">{contest.title}</Link></h2><p className="mt-3 line-clamp-3 text-sm leading-6 text-body">{contest.description}</p><div className="mt-auto flex items-end justify-between gap-4 pt-6"><div><p className="text-xs text-muted">Призовой фонд</p><p className="mt-1 font-bold text-primary">{contest.prize.toLocaleString('ru-RU')} ₸</p></div><span className="text-xs text-muted">{contest.participants} участников</span></div></div></article>
}

export function ContestsPage() {
  const [params, setParams] = useSearchParams(); const query = params.get('q') ?? ''; const category = params.get('category') ?? 'all'; const sort = params.get('sort') ?? 'new'
  const contests = useMemo(() => { const result = getContests().filter((contest) => { const matchesCategory = category === 'all' || contest.category === category; const haystack = `${contest.title} ${contest.description}`.toLocaleLowerCase('ru'); return matchesCategory && (!query || haystack.includes(query.toLocaleLowerCase('ru'))) }); return sort === 'prize' ? result.sort((a, b) => b.prize - a.prize) : result }, [category, query, sort])
  const update = (values) => { const next = new URLSearchParams(params); Object.entries(values).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); setParams(next, { replace: true }) }
  return <main className="min-h-screen"><Container className="pb-16 pt-9 md:pt-12"><PageHeading>Конкурсы <span className="text-accent">для креаторов</span></PageHeading><p className="mx-auto mt-3 max-w-xl text-center text-sm text-muted">Выберите конкурс, предложите свою идею и получите награду за лучший результат.</p><SearchBar key={query} defaultValue={query} placeholder="Найти конкурс" buttonLabel="Найти" onSearch={(value) => update({ q: value })} className="mx-auto mt-8 max-w-2xl" /><div className="mt-7 flex flex-col gap-4 border-b border-line pb-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-2 overflow-x-auto pb-1"><Chip variant="ghost" onClick={() => update({ category: '' })} className={category === 'all' ? 'border-primary bg-primary text-white' : ''}>Все</Chip>{['Дизайн', 'Разработка'].map((item) => <Chip key={item} variant="ghost" onClick={() => update({ category: item })} className={category === item ? 'border-primary bg-primary text-white' : ''}>{item}</Chip>)}</div><div className="flex items-center gap-3"><Button to={ROUTES.createContest}>Создать конкурс</Button><Dropdown label="Сортировка" options={SORT_OPTIONS} value={sort} onChange={(value) => update({ sort: value })} /></div></div>{contests.length ? <div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{contests.map((contest) => <ContestCard key={contest.id} contest={contest} />)}</div> : <EmptyState title="Конкурсы не найдены" text="Попробуйте изменить запрос или категорию." className="mt-10" />}</Container></main>
}