import { Link, useParams } from 'react-router-dom'
import { Avatar, Button, Container, EmptyState } from '@/components/ui'
import { ROUTES } from '@/constants/routes'
import { getContest } from '@/services/dataService'

const formatDate = (date) => new Intl.DateTimeFormat('ru-RU', { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(date))

export function ContestDetailPage() {
  const { id } = useParams(); const contest = getContest(id)
  if (!contest) return <Container className="py-20"><EmptyState title="Конкурс не найден" text="Возможно, конкурс уже завершён или ссылка устарела." action={<Button to={ROUTES.contests}>К списку конкурсов</Button>} /></Container>
  return <main className="min-h-screen"><Container className="pb-16 pt-8 md:pt-12"><Link to={ROUTES.contests} className="text-sm text-muted hover:text-primary">← Все конкурсы</Link><div className="mt-6 grid gap-10 lg:grid-cols-[minmax(0,1fr)_330px]"><article><div className="aspect-[16/7] overflow-hidden rounded-2xl bg-lavender"><img src={contest.cover} alt="" className="size-full object-cover" /></div><p className="mt-7 text-sm font-medium text-primary">{contest.category}</p><h1 className="mt-2 text-3xl font-bold leading-tight md:text-4xl">{contest.title}</h1><p className="mt-5 max-w-3xl text-sm leading-7 text-body">{contest.description}</p><section className="mt-9 border-t border-line pt-7"><h2 className="text-xl font-bold">Что нужно сделать</h2><ul className="mt-4 list-disc space-y-3 pl-5 text-sm leading-6 text-body">{contest.requirements.map((item) => <li key={item}>{item}</li>)}</ul></section><section className="mt-9 border-t border-line pt-7"><h2 className="text-xl font-bold">Работы участников</h2>{contest.submissions.length ? <div className="mt-5 grid gap-4 sm:grid-cols-2">{contest.submissions.map((submission) => <div key={submission.id} className="overflow-hidden rounded-xl border border-line bg-white"><img src={submission.cover} alt="" className="aspect-[4/3] w-full object-cover" /><div className="p-4"><p className="font-semibold">{submission.title}</p><p className="mt-1 text-xs text-muted">{submission.author}</p></div></div>)}</div> : <p className="mt-4 text-sm text-muted">Первые работы появятся здесь после публикации участниками.</p>}</section></article><aside className="h-fit rounded-2xl border border-line bg-white p-6 shadow-soft lg:sticky lg:top-8"><p className="text-sm text-muted">Призовой фонд</p><p className="mt-1 text-3xl font-bold text-primary">{contest.prize.toLocaleString('ru-RU')} ₸</p><dl className="mt-7 space-y-4 border-y border-line py-5 text-sm"><div className="flex justify-between gap-4"><dt className="text-muted">Приём работ до</dt><dd className="font-medium">{formatDate(contest.deadline)}</dd></div><div className="flex justify-between gap-4"><dt className="text-muted">Участников</dt><dd className="font-medium">{contest.participants}</dd></div></dl><Button to={ROUTES.login} fullWidth className="mt-6">Участвовать</Button><p className="mt-3 text-center text-xs leading-5 text-muted">Авторизуйтесь, чтобы отправить работу на конкурс</p><div className="mt-7 flex items-center gap-3 border-t border-line pt-5"><Avatar name={contest.customer} size={40} /><div><p className="text-xs text-muted">Организатор</p><p className="text-sm font-semibold">{contest.customer}</p></div></div></aside></div></Container></main>
}