import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button, Container, Input, PageHeading, Select, Stepper, Textarea } from '@/components/ui'
import { CATEGORIES } from '@/data/mock/categories'
import { ROUTES } from '@/constants/routes'
import { useAuth } from '@/hooks/useAuth'
import { createContest } from '@/services/dataService'

const STEPS = ['Основное', 'Описание', 'Условия', 'Публикация']

export function CreateContestPage() {
  const { user } = useAuth(); const navigate = useNavigate(); const [step, setStep] = useState(0); const [errors, setErrors] = useState({}); const [values, setValues] = useState({ title: '', category: '', description: '', requirements: '', prize: '', deadline: '' })
  const setField = (field, value) => { setValues((current) => ({ ...current, [field]: value })); setErrors((current) => ({ ...current, [field]: '' })) }
  const validate = () => { const next = {}; if (step === 0 && values.title.trim().length < 6) next.title = 'Название должно быть не короче 6 символов'; if (step === 0 && !values.category) next.category = 'Выберите категорию'; if (step === 1 && values.description.trim().length < 30) next.description = 'Добавьте описание не менее 30 символов'; if (step === 2 && (!Number(values.prize) || Number(values.prize) < 1000)) next.prize = 'Минимальный призовой фонд — 1 000 тенге'; if (step === 2 && !values.deadline) next.deadline = 'Укажите дату окончания'; setErrors(next); return Object.keys(next).length === 0 }
  const submit = (event) => { event.preventDefault(); if (!validate()) return; if (step < STEPS.length - 1) { setStep((current) => current + 1); return } const contest = createContest({ ...values, title: values.title.trim(), description: values.description.trim(), requirements: values.requirements.split('\n').map((item) => item.trim()).filter(Boolean), prize: Number(values.prize) }, user?.id); navigate(ROUTES.contest(contest.id)) }
  return <main className="min-h-screen"><Container className="max-w-5xl pb-16 pt-9 md:pt-12"><PageHeading>Создание <span className="text-accent">конкурса</span></PageHeading><Stepper steps={STEPS} current={step} className="mx-auto mt-8 max-w-3xl" /><section className="mt-8 rounded-2xl border border-line bg-white p-5 shadow-soft md:p-9"><form onSubmit={submit} noValidate><div className="min-h-[300px]">{step === 0 && <div className="grid gap-5 md:grid-cols-2"><Input label="Название конкурса" required maxLength={100} placeholder="Например, разработать логотип бренда" value={values.title} error={errors.title} className="md:col-span-2" onChange={(event) => setField('title', event.target.value)} /><Select label="Категория" required value={values.category} error={errors.category} placeholder="Выберите категорию" options={CATEGORIES.map((item) => ({ value: item.title, label: item.title }))} onChange={(event) => setField('category', event.target.value)} /></div>}{step === 1 && <div className="max-w-3xl"><h2 className="text-lg font-semibold">Опишите задачу</h2><p className="mt-1 text-sm text-muted">Чем подробнее будет бриф, тем точнее будут предложения участников.</p><Textarea label="Описание конкурса" required maxLength={2000} value={values.description} error={errors.description} hint="Минимум 30 символов" className="mt-6" onChange={(event) => setField('description', event.target.value)} /></div>}{step === 2 && <div className="max-w-3xl"><h2 className="text-lg font-semibold">Условия конкурса</h2><Textarea label="Что должен предоставить участник" value={values.requirements} hint="Каждое требование с новой строки" className="mt-6" onChange={(event) => setField('requirements', event.target.value)} /><div className="mt-5 grid gap-5 sm:grid-cols-2"><Input label="Призовой фонд, тенге" required type="number" min="1000" step="1000" value={values.prize} error={errors.prize} onChange={(event) => setField('prize', event.target.value)} /><Input label="Приём работ до" required type="date" value={values.deadline} error={errors.deadline} onChange={(event) => setField('deadline', event.target.value)} /></div></div>}{step === 3 && <div className="max-w-2xl"><h2 className="text-lg font-semibold">Проверьте конкурс</h2><dl className="mt-6 space-y-4 rounded-xl bg-surface p-5 text-sm"><div><dt className="text-muted">Название</dt><dd className="mt-1 font-semibold">{values.title}</dd></div><div><dt className="text-muted">Категория</dt><dd className="mt-1">{values.category}</dd></div><div><dt className="text-muted">Призовой фонд</dt><dd className="mt-1 font-semibold text-primary">{Number(values.prize).toLocaleString('ru-RU')} ₸</dd></div></dl></div>}</div><div className="mt-8 flex gap-3">{step > 0 && <Button type="button" variant="soft" size="lg" onClick={() => setStep((current) => current - 1)}>Назад</Button>}<Button type="submit" size="lg" fullWidth>{step === STEPS.length - 1 ? 'Опубликовать конкурс' : 'Далее'}</Button></div></form></section></Container></main>
}