export const ROUTES = {
  home: '/',
  exchange: '/exchange',
  works: '/works',
  work: (id) => `/works/${id}`,
  editWork: (id) => `/works/${id}/edit`,
  order: (id) => `/orders/${id}`,
  contests: '/contests',
  contest: (id) => `/contests/${id}`,
  freelancers: '/freelancers',
  profile: (id) => `/profile/${id}`,
  account: '/account',
  accountEdit: '/account/edit',
  completed: '/completed',
  chat: '/chat',
  wallet: '/wallet',
  purchases: '/purchases',
  myOrders: '/my-orders',
  favorites: '/favorites',
  createWork: '/works/create',
  createOrder: '/orders/create',
  createContest: '/contests/create',
  search: '/search',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
}
